services:

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - find_the_dog_network
    command: npm start
    
networks:
  find_the_dog_network:
    external: true
